// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const DEFAULT_DEV_DATABASE_URL = "file:./prisma/dev.db";

function getDatabaseUrl() {
  const databaseUrl = process.env["DATABASE_URL"];
  if (databaseUrl && databaseUrl.trim().length > 0) return databaseUrl;
  if (process.env["NODE_ENV"] === "production") return undefined;
  return DEFAULT_DEV_DATABASE_URL;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
